version: '3.9'

services:
  web-icecms:
    image: nginx:latest
    container_name: web-icecms
    ports:
      - '8181:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm-icecms
  php-fpm-icecms:
    container_name: php-fpm-icecms
    build:
      context: docker/8.2-fpm
      dockerfile: "Dockerfile"
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    depends_on:
      - db-icecms
      - redis-icecms
    volumes:
      - ./:/var/www/html
  db-icecms:
    container_name: db-icecms
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33066:3306
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: localRoot
      MARIADB_DATABASE: ice2
      MARIADB_ROOT_HOST: '%' # allow root login from any host
  redis-icecms:
    container_name: redis-icecms
    image: redis:latest
    ports:
      - "6382:6379"
  elastic:
    container_name: elastic-icecms
    image: elasticsearch:8.12.2
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - db-icecms
      - redis-icecms