version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8181:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: docker/8.2-fpm
      dockerfile: "Dockerfile"
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www/html
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33066:3306
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: localRoot
      MARIADB_DATABASE: ice2
      MARIADB_ROOT_HOST: '%' # allow root login from any host
  redis:
    image: redis:latest
    ports:
      - "6382:6379"